spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/User_Service
spring.datasource.username=postgres
spring.datasource.password=PASSWORD

#let Hibernate auto-create your tables from your entity classes.
# update will create/alter tables to match your @Entity classes automatically.
spring.jpa.hibernate.ddl-auto=update
secret_key=c9053bb57927ac06e290b84c3b93a470a7e57b5a92a98f343b40bf8dbebf5495
expiration= 60000
refresh-expiration= 604800000
refresh-token-retention-days= 7